### ISSUE TITLE
Missing Newest Pictures

### ISSUE THREAD

**Issue by pimp1310** [lukelalo/gallery-card#2]
Here is my gallery Card code

`type: custom:gallery-card
entities:
  - path: media-source://media_source/esp32_cam/
    recursive: true
    include_video: false
include_images: true
maximum_files: 20
file_name_format: HH:mm:ss-DD.MM.YY
show_reload: true
menu_alignment: bottom
parsed_date_sort: true
reverse_sort: true
random_sort: false
recursive: true
caption_format: DD-MM-YYYY HH:mm
`

my problem is he doesnt shows all images, the newest were ignored, he shows the last from 18.06.2024 18:53.

but i have newer pictures, here is a screenshot.
he stops by the folder named 18 but it gives 19 and 20.

my file format 

` 06:54:55-20.06.24.jpg`

![missing_folder](https://github.com/lukelalo/gallery-card/assets/6306057/544df9c0-7c51-4611-ab52-d1c66d963b18)

![missing_1](https://github.com/lukelalo/gallery-card/assets/6306057/ede4beee-f103-4959-aa1b-bf68781a6530)

**Comment by lukelalo** [comment]
Please check your sensor.snaps.See #1
