### ISSUE TITLE
Request: make full filename available as an attribute/property, when clicking on a picture/video

### ISSUE THREAD

**Issue by sn00zerman** [lukelalo/gallery-card#3]
Hello,

I love this beautiful frontend integration, however I’m missing one feature :-)
Can you please make the last selected video/picture available as an attribute, so I can create my own automation for
the selected file ?
I use this component to show a list of my own recordings of my ip cameras.
I need to go into the “media”, to select and delete files.
It would ne nice if the filename of the last clicked image/video is available in an attribute, so I can add a button in the dashboard,
And make my own automation to do things with the file (like deleting it for example)

thanks in advance,
Greetings from Belgium,
Kris
-=[https://www.digitalplayground.be]=-
Where fun meets technology …

**Comment by lukelalo** [comment]
Mmm I'm not sure what you are asking for. This component doesn't expose attributes, it only works with sensors and folders existing in your system. As a frontend component it can't generate any entities which you can use to play with on automations
